name: 'Get and cache dependencies'
description: 'Get the dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: node-module-dependencies-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      shell: bash
