name: 'Get and cache dependencies'
description: 'Get the dependencies (via npm) and cache them.'
inputs:
  folder:
    description: The name of the folder. Either backend of frontend
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ${{ inputs.folder }}/node_modules
        key: node-module-dependencies-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: npm ci
      working-directory: ${{ inputs.folder }}
      shell: bash
