name: Run Frontend checks
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:
jobs:
  lint:
    uses: ./.github/workflows/linting.yml
    with:
      folder: frontend
  test:
    needs: lint
    uses: ./.github/workflows/testing.yml
    with:
      folder: frontend
