name: Reusable testing
on:
  workflow_call:
    inputs:
      folder:
        description: The name of the folder. Either backend of frontend
        required: true
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Load and cache dependencies
        uses: ./.github/actions/cache-dependencies
        with:
          folder: ${{ inputs.folder }}
      - name: Test code
        run: npm run test
        working-directory: ${{ inputs.folder }}
